################################################################################
#
# Copyright (c) 2025 Megatile Contributors
#
# Code Generator - Aligned with Triton-distributed
#
# Generates mega kernel dynamically based on registered tasks.
#
################################################################################
from typing import List, Dict, Tuple
import textwrap
from dataclasses import dataclass
from .registry import registry
from .task_base import TaskBase, CodeGenKey, MAX_NUM_TENSOR_DIMS


@dataclass
class CodeGenOptions:
    enable_profiling: bool = False
    enable_runtime_scheduler: bool = False
    enalbe_task_prefetch: bool = False


def make_mega_kernel_src(
    tasks_dispatch_code: str,
    task_types_and_str: Dict[int, str],
    codegen_options: CodeGenOptions,
    max_deps_entries: int,
    max_scoreboard_size: int,
    tensor_list: List,
) -> Tuple[str, Dict[int, str]]:
    """
    Generate the mega kernel source code.
    
    Args:
        tasks_dispatch_code: Generated dispatch code for tasks
        task_types_and_str: Mapping from task_type to task name
        codegen_options: Code generation options
        max_deps_entries: Max number of dependency entries (compile-time constant)
        max_scoreboard_size: Max scoreboard size (compile-time constant)
    """
    from megatile.kernels import release_tile
    
    src = f'''################################################################################
# Mega Kernel generated by Megatile
# Aligned with Triton-distributed architecture
################################################################################

import tilelang
import tilelang.language as T
from megatile.kernels.task_context import wait_deps, release_tile, TILE_READY_SIGNAL
from megatile.kernels.linear import tile_wise_matmul_compute, linear_task_compute
from megatile.kernels.norm import rmsnorm_task_compute
from megatile.kernels.activation import act_mul_up_tile_compute, silu_mul_up_task_compute

@tilelang.jit
def MEGA_TILELANG_KERNEL(
    INT_PER_TASK: int,
    MAX_LAYER_ID: int,
    MAX_TASK_ID: int,
    MAX_NUM_TILES_PER_OP: int,
    NUM_SMS: int,
    MAX_TASKS_PER_SM: int,
    num_warps: int,
):
    """
    Mega kernel with task queue processing per SM.
    Aligned with Triton-distributed's MEGA_TRITON_KERNEL.
    """
    # Define shapes for prim_func (like the example does)
    work_queues_shape = (MAX_TASKS_PER_SM, NUM_SMS, INT_PER_TASK)
    num_tasks_per_sm_shape = (NUM_SMS,)
    scoreboard_flat_shape = ({max_scoreboard_size},)
    task_deps_shape = ({max_deps_entries}, 2)
{chr(10).join(f'    tensor_{i}_shape = {tuple(tensor.shape)}' for i, tensor in enumerate(tensor_list)) if tensor_list else ''}
    
    @T.prim_func
    def mega_kernel_impl(
        work_queues: T.Tensor(work_queues_shape, T.int64),
        num_tasks_per_sm: T.Tensor(num_tasks_per_sm_shape, T.int32),
        scoreboard_flat: T.Tensor(scoreboard_flat_shape, T.int32),
        task_deps: T.Tensor(task_deps_shape, T.int32),
{chr(10).join(f'        tensor_{i}: T.Tensor(tensor_{i}_shape, T.bfloat16),' for i, tensor in enumerate(tensor_list)) if tensor_list else ''}
    ) -> None:
        WARP_SIZE = 32
        NUM_THREADS = num_warps * WARP_SIZE
        
        # Work queue offsets
        TASK_TYPE_OFFSET = 0
        LAYER_ID_OFFSET = 1
        TASK_ID_OFFSET = 2
        TILE_ID_OFFSET = 3
        DEPS_START_OFFSET = 4
        DEPS_END_OFFSET = 5
        IO_TENSORS_OFFSET = 6
        
        with T.Kernel(NUM_SMS, threads=NUM_THREADS) as sm_id:
            cur_task_idx = T.alloc_var(T.int32)
            cur_task_idx = 0
            num_tasks = num_tasks_per_sm[sm_id]
            
            while cur_task_idx < num_tasks:
                task_type = work_queues[cur_task_idx, sm_id, TASK_TYPE_OFFSET]
                layer_id = work_queues[cur_task_idx, sm_id, LAYER_ID_OFFSET]
                task_id = work_queues[cur_task_idx, sm_id, TASK_ID_OFFSET]
                tile_id = work_queues[cur_task_idx, sm_id, TILE_ID_OFFSET]
                deps_start = work_queues[cur_task_idx, sm_id, DEPS_START_OFFSET]
                deps_end = work_queues[cur_task_idx, sm_id, DEPS_END_OFFSET]
                
                # Wait for dependencies using macro (like release_tile)
                wait_deps(scoreboard_flat, task_deps, deps_start, deps_end, num_warps)
                
                # Dispatch based on task_type
{textwrap.indent(tasks_dispatch_code.strip(), '                ')}
                
                # Release tile - aligned with Triton's release_tile(self, task_base_info, tile_id)
                # Aligned with Triton: sb_set_base_ptr = self.task_scoredboard_start(task_base_info)
                # task_scoredboard_start: sb_layer_offset = layer_id * MAX_TASK_ID * MAX_NUM_TILES_PER_OP
                #                        sb_set_base_ptr = scoreboard_table + sb_layer_offset + task_id * MAX_NUM_TILES_PER_OP
                base_offset = layer_id * MAX_TASK_ID * MAX_NUM_TILES_PER_OP + task_id * MAX_NUM_TILES_PER_OP
                release_tile(scoreboard_flat, base_offset + tile_id)
                
                cur_task_idx = cur_task_idx + 1
    
    return mega_kernel_impl
'''
    return src, task_types_and_str


class CodeGenerator:

    def __init__(self):
        self._condition_and_codes: Dict[int, List[Tuple[CodeGenKey, str]]] = {}
        self._variable_names: Dict[str, str] = {
            "layer_id": "layer_id",
            "task_id": "task_id",
            "task_type": "task_type",
        }
        self._task_types_and_str: Dict[int, str] = {}

    def generate_task_dispatch_code(self, condition: CodeGenKey, code: str, is_first_branch=True) -> str:
        if condition.only_use_task_type():
            return f"""
{'if' if is_first_branch else 'elif'} {self._variable_names["task_type"]} == {condition.task_type}: # {self._task_types_and_str[condition.task_type]}
{textwrap.indent(code.strip(), '    ')}
"""
        else:
            return f"""
{'if' if is_first_branch else 'elif'} {self._variable_names["task_type"]} == {condition.task_type}: # {self._task_types_and_str[condition.task_type]}
    if {self._variable_names["layer_id"]} == {condition.layer_id} and {self._variable_names["task_id"]} == {condition.task_id}:
{textwrap.indent(code.strip(), '        ')}
"""

    def generate_for_each_task(self, condition: CodeGenKey, code: str, is_first_branch=True):
        return f"""
{'if' if is_first_branch else 'elif'} {self._variable_names["layer_id"]} == {condition.layer_id} and {self._variable_names["task_id"]} == {condition.task_id}:
{textwrap.indent(code.strip(), '    ')}
"""

    def generate_for_each_task_type(self, key_and_tasks_list, is_first_branch=True) -> str:
        assert len(key_and_tasks_list) > 0
        same_code = True
        task_type = key_and_tasks_list[0][0].task_type
        for key, code in key_and_tasks_list:
            if code != key_and_tasks_list[0][1]:
                same_code = False
        if same_code:
            code = key_and_tasks_list[0][1]
            return f"""
{'if' if is_first_branch else 'elif'} {self._variable_names["task_type"]} == {task_type}: # {self._task_types_and_str[task_type]}
{textwrap.indent(code.strip(), '    ')}
"""
        else:
            # each op may split into multi task, these tasks have same (task_type, layer_id, task_id)
            # only need to generate code once for these tasks
            already_generated = set()
            all_codes = ""
            is_first_task = True
            for key, code in key_and_tasks_list:
                if key in already_generated:
                    continue
                already_generated.add(key)
                cur_code = self.generate_for_each_task(key, code, is_first_task)
                all_codes += cur_code
                is_first_task = False
            return f"""
{'if' if is_first_branch else 'elif'} {self._variable_names["task_type"]} == {task_type}: # {self._task_types_and_str[task_type]}
{textwrap.indent(all_codes.strip(), '    ')}
"""
    
    def generate_code(self, tasks: List['TaskBase'], codegen_options: CodeGenOptions, max_deps_entries: int, max_scoreboard_size: int) -> Tuple[str, Dict[int, str], List]:
        self._condition_and_codes.clear()
        self._task_types_and_str.clear()

        # Collect all unique tensors from tasks (TileLang needs explicit tensor arguments)
        tensor_set = set()
        tensor_list = []
        tensor_to_index = {}
        
        for task in tasks:
            # Collect tensors from io_tensors
            for io_group in task.io_tensors:
                for tensor in io_group:
                    if tensor not in tensor_set:
                        tensor_set.add(tensor)
                        tensor_to_index[tensor] = len(tensor_list)
                        tensor_list.append(tensor)

        for task in tasks:
            key = task.get_codegen_key(task.layer_id, task.task_id)
            assert isinstance(key, CodeGenKey)
            task_type = type(task)
            codegen_func = registry.get_codegen(task_type)
            code = codegen_func(task, tensor_to_index=tensor_to_index)
            if key.task_type not in self._condition_and_codes:
                self._condition_and_codes[key.task_type] = []
            self._condition_and_codes[key.task_type].append((key, code))
            self._task_types_and_str[key.task_type] = task_type.__name__

        # TODO: branch optimization
        is_first_branch = True
        tasks_dispatch_code = ""

        for task_type, key_and_tasks_list in self._condition_and_codes.items():
            tasks_dispatch_code += self.generate_for_each_task_type(key_and_tasks_list, is_first_branch)
            is_first_branch = False

        mege_kernel_src, self._task_types_and_str = make_mega_kernel_src(tasks_dispatch_code, self._task_types_and_str,
                                                                         codegen_options, max_deps_entries, max_scoreboard_size, tensor_list)
        return mege_kernel_src, self._task_types_and_str, tensor_list
